version: '3'
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Docker/Dockerfile
    env_file:
      - .env.develop
    network_mode: app_network
    volumes:
      - ./Database:/app/Database

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    network_mode: app_network

networks:
  app_network:
    driver: bridge 